#!/bin/sh
if mountpoint -q /target; then
	echo "Installing docker-tools to /target"
	cp /docker-tools/* /target
else
	echo "/target is not a mountpoint."
	echo "You can either:"
	echo "- re-run this container with -v /usr/local/bin:/target"
	echo "- extract the docker-tools folder (located at /)"
fi
