#!/bin/sh
if mountpoint -q /target; then
	echo "Updating docker-tools"
	cd /docker-tools
	git fetch origin
 	git reset --hard origin/master
 	chmod +x /docker-tools/bin/*
	echo "Installing docker-tools to /target"
	cp -r bin/* /target
else
	echo "/target is not a mountpoint."
	echo "You can either:"
	echo "- re-run this container with -v /usr/local/bin:/target"
	echo "- extract the /docker-tools/bin folder"
fi
